import { JSONSchema7Type, JSONSchema7TypeName } from "json-schema";

/**
 * This class handles creating the schema for object schemas and editing them.
 * Internally, a more developer friendly data structure gets used than the schema itself,
 * which only gets generated by toSchema().
 */
interface IVeoObjectSchema {}

interface IVeoObjectSchemaAttribute {
  title: string
  type: JSONSchema7TypeName
  format?: string
  pattern?: string
}

export default class ObjectSchemaHelper {
  constructor(objectSchema?: IVeoObjectSchema) {
    if(objectSchema) {

    }
  }


  public toSchema(): IVeoObjectSchema {
    return {}
  }
}
